# Request
# ======  
# exec_time is the expected time of execution of a task sent to the buffer, from the perspective of 
# when the buffer recieved it.

builtin_interfaces/Time exec_time
---
# Response
# ========
# actual execution time, buffers will find the nearest match.
# img that matches execution time.

builtin_interfaces/Time actual_time
sensor_msgs/Image img
---
# Feedback
# ========
# Percentile of what is processed so far.

int8 percent_processed