# Update GPS state, this will return the state
# update has been completed

# Support for NEO-6M, note that package ublox_gps, this will publish to topics
# /fix and /vel
bool override_state false
sensor_msgs/NavSatFix gps_tx

---

sensor_msgs/NavSatFix gps_rx