# Generic monitor command, provided to simplify action common, and plugin interfaces.
# Note that the interface will set the specific action, and only one action be provided
# by the Node.
#
# Returns current state of sensor provided in command
#

# Request GID
unique_identifier_msgs/UUID request_id
int32 command
---
unique_identifier_msgs/UUID response_id
int64 sequence_id
rr_interfaces/Action action

# STATUSES are:
# 0 : SUCCESS
# 1 : FAILED
# 2 : TIMEOUT
# 4 : CRITICAL
byte status